#!/usr/bin/env python3
import sys

from atcodertools.tools.envgen import main as envgen_main
from atcodertools.tools.tester import do_test

if __name__ == '__main__':
    if len(sys.argv) < 2 or sys.argv[1] not in ("gen", "test"):
        print("Usage:")
        print("{} gen -- to generate workspace".format(sys.argv[0]))
        print("{} test -- to test codes in your workspace".format(sys.argv[0]))
        sys.exit(-1)

    prog = " ".join(sys.argv[:2])
    args = sys.argv[2:]

    if sys.argv[1] == "gen":
        envgen_main(prog, args)

    if sys.argv[1] == "test":
        do_test()
