import java.io.*;
import java.util.*;

class Main {

    // Generated by x.x.x
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long T;
        T = sc.nextLong();
        long X;
        X = sc.nextLong();
        solve(T, X);
    }

    static void solve(long T, long X){

    }
}

