import java.io.*;
import java.util.*;

class Main {

    // Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        final Scanner sc = new Scanner(System.in);
        long T;
        T = sc.nextLong();
        long X;
        X = sc.nextLong();
        solve(T, X);
    }

    static void solve(long T, long X){

    }
}
