#!/usr/bin/env julia
{% if prediction_success %}
{% endif %}
{% if mod or yes_str or no_str %}
{% endif %}
{% if mod %}
const MOD = {{ mod }}
{% endif %}
{% if yes_str %}
const YES = "{{ yes_str }}"
{% endif %}
{% if no_str %}
const NO = "{{ no_str }}"
{% endif %}
{% if prediction_success %}

function solve({{ formal_arguments }})
{% if query_dispatch_skeleton %}
{{ query_dispatch_skeleton }}
{% else %}

{% endif %}
end
{% endif %}

# Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
function main()
    {% if prediction_success %}
    tokens = Channel{String}(32)
    Task() do
        for line in eachline(@static VERSION < v"0.6" ? STDIN : stdin)
            for token in split(chomp(line))
                put!(tokens, token)
            end
        end
        close(tokens)
    end |> schedule
{% if multi_case %}
    {{ prefix_input_part }}
    for {{ case_loop_var }} in 1:{{ case_count_var }}
        {{ case_input_part | replace('\n', '\n' ~ "    ") }}
        solve({{ actual_arguments }})
    end
{% else %}
    {{ input_part }}
    solve({{ actual_arguments }})
{% endif %}
    {% else %}
    # Failed to predict input format
    {% endif %}
end

isempty(ARGS) && main()
