import java.io.*;
import java.util.*;

class Main {
    {% if mod %}
    static final long MOD = {{ mod }};
    {% endif %}
    {% if yes_str %}
    static final String YES = "{{ yes_str }}";
    {% endif %}
    {% if no_str %}
    static final String NO = "{{ no_str }}";
    {% endif %}

    // Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
    public static void main(String[] args) throws Exception {
        {% if prediction_success %}
{% if multi_case %}
        {{ prefix_input_part }}
        for(int {{ case_loop_var }} = 0 ; {{ case_loop_var }} < {{ case_count_var }} ; {{ case_loop_var }}++){
            {{ case_input_part | replace('\n', '\n' ~ "    ") }}
            solve({{ actual_arguments }});
        }
{% else %}
        {{ input_part }}
        solve({{ actual_arguments }});
{% endif %}
        {% else %}
        // Failed to predict input format
        {% endif %}
    }

    {% if prediction_success %}
    static void solve({{ formal_arguments }}){

    }
    {% endif %}
}
