#include <iostream>
#include <sstream>
#include <fstream>
#include <string>
#include <vector>
#include <deque>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <algorithm>
#include <functional>
#include <utility>
#include <bitset>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <cstdio>
#include <cassert>
using namespace std;

{% if mod %}
const long long MOD = {{ mod }};
{% endif %}
{% if yes_str %}
const string YES = "{{ yes_str }}";
{% endif %}
{% if no_str %}
const string NO = "{{ no_str }}";
{% endif %}

{% if prediction_success %}
void solve({{ formal_arguments }}){

}
{% endif %}

// Generated by {{ atcodertools.version }} {{ atcodertools.url }}  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    {% if prediction_success %}
{% if multi_case %}
    {{ prefix_input_part }}
    for(int {{ case_loop_var }} = 0 ; {{ case_loop_var }} < {{ case_count_var }} ; {{ case_loop_var }}++){
        {{ case_input_part | replace('\n', '\n' ~ "    ") }}
        solve({{ actual_arguments }});
    }
{% else %}
    {{input_part}}
    solve({{ actual_arguments }});
{% endif %}
    {% else %}
    // Failed to predict input format
    {% endif %}
    return 0;
}
