import java.io.*;
import java.util.*;

class Main {
	static final String YES = "Yes";
	static final String NO = "No";

	// Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
	public static void main(String[] args) throws Exception {
		final Scanner sc = new Scanner(System.in);
		long A;
		A = sc.nextLong();
		long B;
		B = sc.nextLong();
		long C;
		C = sc.nextLong();
		solve(A, B, C);
	}

	static void solve(long A, long B, long C){
		if(A + B >= C){
			System.out.println(YES);
		}else{
			System.out.println(NO);
		}
	}
}
