base_indent = 1
insert_space_around_operators = false

# global変数宣言時の接頭辞
global_prefix = ""
input_part_prefix = "auto input = stdin.byLine.map!split.joiner;"
newline_after_input = true

# ループ
[loop]
header = "foreach ({loop_var}; 0 .. cast(size_t) ({length})) {{"
footer = "}}"

# タイプ
[type]
int = "long"
float = "double"
str = "string"

# デフォルト値
[default]
int = "0"
float = "0.0"
str = '""'

# 引数
[arg]
int = "long {name}"
float = "double {name}"
str = "string {name}"
seq = "{type}[] {name}"
2d_seq = "{type}[][] {name}"

# 配列アクセス
[access]
seq = "{name}[{index}]"
2d_seq = "{name}[{index_i}][{index_j}]"

# 宣言
[declare]
int = "long {name};"
float = "double {name};"
str = "string {name};"
seq = "{type}[] {name};"
2d_seq = "{type}[][] {name};"

# 確保
[allocate]
seq = "{name} = new {type}[](cast(size_t) ({length}));"
2d_seq = "{name} = new {type}[][](cast(size_t) ({length_i}), cast(size_t) ({length_j}));"
# 宣言と確保
[declare_and_allocate]
seq = "{type}[] {name} = new {type}[](cast(size_t) ({length}));"
2d_seq = "{type}[][] {name} = new {type}[][](cast(size_t) ({length_i}), cast(size_t) ({length_j}));"

# 入力
[input]
int = "{name} = input.front.to!long;\ninput.popFront;"
float = "{name} = input.front.to!double;\ninput.popFront;"
str = "{name} = input.front.to!string;\ninput.popFront;"


