name: Check no style violation

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Check styles
        run: |
          poetry run flake8 --ignore=E501,W503,W605 --exclude=atcodertools/tools/templates/,tests/resources/test_codegen/ atcodertools tests
          poetry run autopep8 -r . --exclude 'default_template.py,test_codegen' --diff | tee check_autopep8
          test ! -s check_autopep8
